### PR TITLE
Demangle Function Name from Async Calls

### LINKED ISSUE #147: Ideas on demangling the function names of async tasks?
Hi there,

I'm currently trying to clean up how our C# stack-traces look in Sentry. You merged my PR last week to add the 'in-app' flag which has made a _huge_ difference. Now we only see our code by default in stack traces.

The next piece I want to try to tackle is the names of async functions, but I thought it best to open an issue before writing any code.

Our stack-traces (from the dotnet runtime) have items that look like this: (and they appear the same in Sentry:)

`Flipdish.Web.Controllers.PollApiController+<RequestNewOrders>d__4 in MoveNext at line 37:13`

Which comes from this code:

```C#
public async Task<ActionResult> RequestNewOrders()
{
  var requestTime = System.Web.HttpContext.Current.Timestamp;
  var userId = User.Identity.GetUserId<int>();
  // The following is line 37, which is 'MoveNext' I guess:
  IEnumerable<PreviousOrderDm> result = await _posApiService.RequestNewOrders(requestTime, userId); 
// ...
}

```

At first glance, it looks like the C# compiler is creating a little function with a random name in place of the `async`/`await` syntactic sugar, which results in the method name `PollApiController+<RequestNewOrders>d__4 in MoveNext`.

I wonder is there a way to get a nicer looking name than that?

In the past I have worked on Clojure projects and run into the same problem. The Clojure compiler creates JVM function with similar names; Clojure functions can have characters in the function name that the JVM does not allow, such as `?` and `!`. The Clojure compiler will replace these characters with `_QMARK_` and `_BANG`. A function named `list?` in Clojure will be named `list_QMARK_` when compiled for the JVM. Clojure exception loggers will typically have a demangling step which will reverse these replacements in the function names, so that the function name reported to Sentry, for example, would be `list?`. The happens in the exception logging client before the JSON is sent to the logger.

Here is such a look-up table.

https://github.com/mmcgrana/clj-stacktrace/blob/master/src/clj_stacktrace/core.clj#L22-L34

I wonder if it would be possible to do the same in raven-csharp?

We might be able to change:

`Flipdish.Web.Controllers.PollApiController+<RequestNewOrders>d__4 in MoveNext at line 37:13`

to:

`Flipdish.Web.Controllers.PollApiController.RequestNewOrders in async task at line 37:13`

What do you think? Good idea/crazy idea?

### PR DESCRIPTION
**Pull request by marcomorain**
When the Microsoft cs.exe compiler compiles some modern C# features,
such as async/await calls, it can create synthetic function names that
do not match the function names in the original source code. Here we
reverse some of these transformations, so that the function and module
names that appears in the Sentry UI will match the function and module
names in the original source-code.

Fixes #147

### CODE REVIEW

File: src/app/SharpRaven/Data/ExceptionFrame.cs [hunk 1]
```diff
@@ -227,8 +229,42 @@ public override string ToString()
...
+        /// </summary>
+        /// <para>
+        /// When the Microsoft cs.exe compiler compiles some modern C# features,
+        /// such as async/await calls, it can create synthetic function names that
+        /// do not match the function names in the original source code. Here we
+        /// reverse some of these transformations, so that the function and module
+        /// names that appears in the Sentry UI will match the function and module
+        /// names in the original source-code.
+        /// </para>
+        private void demangleFunctionName()
```
Comment (asbjornu) [inline src/app/SharpRaven/Data/ExceptionFrame.cs]: Uppercase first letter in method names, please. 😃

File: src/tests/SharpRaven.UnitTests/Data/ExceptionFrameTests.cs [hunk 2]
```diff
@@ -77,19 +78,49 @@ public void Constructor_InAppFrames_Identified()
...
                 var frames = new StackTrace(exception, true).GetFrames();
                 var sentryFrames = frames.Select(f => new ExceptionFrame(f)).ToList();
 
                 // The first frame is InApp - (this function).
-                Assert.True(sentryFrames.First().InApp); 
+                Assert.True(sentryFrames.First().InApp);
 
                 // The last frame is InApp (our lambda that divides by zero).
-                Assert.True(sentryFrames.Last().InApp); 
+                Assert.True(sentryFrames.Last().InApp);
```
Comment (asbjornu) [inline src/tests/SharpRaven.UnitTests/Data/ExceptionFrameTests.cs]: Try to avoid touching code that isn't a part of the problem this PR is fixing, please. 😃

**Comment by marcomorain** [comment]
@asbjornu ok - should be ready to rock now 🚀

**Comment by asbjornu** [comment]
@marcomorain: Awesome, thanks!

**Comment by marcomorain** [comment]
Thanks! Im looking forward to deploying this.





On Wed, 5 Oct 2016, at 08:33, Asbjørn Ulsberg wrote:
> Merged #164[1].
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>


Links:

  1. https://github.com/getsentry/raven-csharp/pull/164
  2. https://github.com/getsentry/raven-csharp/pull/164#event-812855780
